name: Tests & Checks
jobs:
  biome_types:
    name: Biome and Types
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.0
      - run: bun check