name: Tests & Checks
on:
  push:
    branches:
      - "**"

jobs:
  biome_and_types:
    name: Biome and Types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.0

      - name: Install Dependencies
        run: bun install

      - name: Check installed tools
        run: |
          echo "Bun version:"
          bun --version
          echo "Biome version:"
          bunx biome --version
          ls -lah

      - name: Run Biome
        run: bunx biome ci . --formatter-enabled=true --linter-enabled=true
      
      - name: Run TypeScript
        run: bunx tsc --noEmit
