name: Tests & Checks
on:
  push:
    branches:
      - '**'

jobs:
  biome_and_types:
    name: Biome and Types
    runs-on: ubuntu-latest
    steps:
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.0

      - name: Run Bun Check
        run: bun check